name: 'Josh Robson Chase'
description: 'Action to publish markdown documents to notion'
author: 'Josh Robson Chase'
inputs:
  notion_token:
    required: true
    description: 'Secret for use with your Notion integration'
runs:
  using: 'node16'
  main: 'dist/index.js'
