name: 'Josh Robson Chase'
description: 'Action to publish markdown documents to notion'
author: 'Josh Robson Chase'
inputs:
  notion_token:
    required: true
    description: 'Secret for use with your Notion integration'
  markdown_root:
    required: true
    description: 'Directory in which to look for markdown files'
  notion_root:
    required: true
    description: 'Database to put the generated documents in'
  github_url:
    required: true
    description: 'GitHub URL to prepend to file paths'
runs:
  using: 'node16'
  main: 'dist/index.js'
